### ISSUE TITLE
Securing internal urls

### ISSUE THREAD

**Issue by meandor** [otto-de/tesla-microservice#31]
is there a way to secure (basic-auth/ip filter) access to internal urls like status page, health, metering page?

if so, can you add it to the readme?

**Comment by alphaone** [comment]
Yes you can.

You can pass a authenticate-fn to the app-status component:
`:app-status (c/using (app-status/new-app-status authenticated?) [:config :handler])`

Such a function will take a config, a user and a password:
`(defn authenticated? [config user password] ...)`

*user* and *password* will be extracted via `ring.middleware.basic-authentication/wrap-basic-authentication`.

The same should be true for the `/metrics` endpoint.

**Comment by meandor** [comment]
readme please?

**Comment by alphaone** [comment]
PRs welcome ;-)

**Comment by meandor** [comment]
See #32
